name: Release
on:
  push:
    tags: ['v*']
permissions:
  contents: read
  id-token: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa  # v5.1.0
